version: '3'
services:
  cocoadb:
    container_name: cocoadb
    image: postgres:9.5
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=cocoa
    - POSTGRES_PASSWORD=cocoa
    networks:
    - core_net
  cocoacore:
    container_name: cocoa
    image: ekmechanes/cocoa-docker
    ports:
    - 9394:8080
    - 8787:8787
    depends_on:
    - cocoadb
    environment:
    - debug=true
    - R_SERVER_HOST=r_server
    - R_SERVER_PORT=6311
    - R_SCRIPTS_PATH=/usr/local/src/deus/scripts
    env_file:
    - dev.env
    networks:
    - core_net
  r_server:
    container_name: r_server
    image: ekmechanes/cocoa-r-server
    ports:
    - 6311:6311
    - 8383:8000
    depends_on:
    - cocoadb
    env_file:
    - dev.env
    networks:
    - core_net
networks:
  core_net:
    driver: bridge